// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: TylerSandbox.proto

package tgsbpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryCallStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnaryCallStringRequest) Reset() {
	*x = UnaryCallStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryCallStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryCallStringRequest) ProtoMessage() {}

func (x *UnaryCallStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryCallStringRequest.ProtoReflect.Descriptor instead.
func (*UnaryCallStringRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryCallStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UnaryCallStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnaryCallStringResponse) Reset() {
	*x = UnaryCallStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryCallStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryCallStringResponse) ProtoMessage() {}

func (x *UnaryCallStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryCallStringResponse.ProtoReflect.Descriptor instead.
func (*UnaryCallStringResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryCallStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UnaryCallIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnaryCallIntRequest) Reset() {
	*x = UnaryCallIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryCallIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryCallIntRequest) ProtoMessage() {}

func (x *UnaryCallIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryCallIntRequest.ProtoReflect.Descriptor instead.
func (*UnaryCallIntRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{2}
}

func (x *UnaryCallIntRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UnaryCallIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UnaryCallIntResponse) Reset() {
	*x = UnaryCallIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryCallIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryCallIntResponse) ProtoMessage() {}

func (x *UnaryCallIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryCallIntResponse.ProtoReflect.Descriptor instead.
func (*UnaryCallIntResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{3}
}

func (x *UnaryCallIntResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ServerStreamStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value                  string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	SendPeriodSeconds      uint32 `protobuf:"varint,2,opt,name=send_period_seconds,json=sendPeriodSeconds,proto3" json:"send_period_seconds,omitempty"`
	CloseAtNthResponse     uint32 `protobuf:"varint,3,opt,name=close_at_nth_response,json=closeAtNthResponse,proto3" json:"close_at_nth_response,omitempty"`
	SendErrorAtNthResponse uint32 `protobuf:"varint,4,opt,name=send_error_at_nth_response,json=sendErrorAtNthResponse,proto3" json:"send_error_at_nth_response,omitempty"`
}

func (x *ServerStreamStringRequest) Reset() {
	*x = ServerStreamStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamStringRequest) ProtoMessage() {}

func (x *ServerStreamStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamStringRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamStringRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{4}
}

func (x *ServerStreamStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ServerStreamStringRequest) GetSendPeriodSeconds() uint32 {
	if x != nil {
		return x.SendPeriodSeconds
	}
	return 0
}

func (x *ServerStreamStringRequest) GetCloseAtNthResponse() uint32 {
	if x != nil {
		return x.CloseAtNthResponse
	}
	return 0
}

func (x *ServerStreamStringRequest) GetSendErrorAtNthResponse() uint32 {
	if x != nil {
		return x.SendErrorAtNthResponse
	}
	return 0
}

type ServerStreamStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServerStreamStringResponse) Reset() {
	*x = ServerStreamStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamStringResponse) ProtoMessage() {}

func (x *ServerStreamStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamStringResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamStringResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStreamStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ServerStreamIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value                  int32  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	SendPeriodSeconds      uint32 `protobuf:"varint,2,opt,name=send_period_seconds,json=sendPeriodSeconds,proto3" json:"send_period_seconds,omitempty"`
	CloseAtNthResponse     uint32 `protobuf:"varint,3,opt,name=close_at_nth_response,json=closeAtNthResponse,proto3" json:"close_at_nth_response,omitempty"`
	SendErrorAtNthResponse uint32 `protobuf:"varint,4,opt,name=send_error_at_nth_response,json=sendErrorAtNthResponse,proto3" json:"send_error_at_nth_response,omitempty"`
}

func (x *ServerStreamIntRequest) Reset() {
	*x = ServerStreamIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamIntRequest) ProtoMessage() {}

func (x *ServerStreamIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamIntRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamIntRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ServerStreamIntRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ServerStreamIntRequest) GetSendPeriodSeconds() uint32 {
	if x != nil {
		return x.SendPeriodSeconds
	}
	return 0
}

func (x *ServerStreamIntRequest) GetCloseAtNthResponse() uint32 {
	if x != nil {
		return x.CloseAtNthResponse
	}
	return 0
}

func (x *ServerStreamIntRequest) GetSendErrorAtNthResponse() uint32 {
	if x != nil {
		return x.SendErrorAtNthResponse
	}
	return 0
}

type ServerStreamIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ServerStreamIntResponse) Reset() {
	*x = ServerStreamIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerStreamIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamIntResponse) ProtoMessage() {}

func (x *ServerStreamIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamIntResponse.ProtoReflect.Descriptor instead.
func (*ServerStreamIntResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{7}
}

func (x *ServerStreamIntResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ClientStreamStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value            string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Close            bool   `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	RespondWithError bool   `protobuf:"varint,3,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
}

func (x *ClientStreamStringRequest) Reset() {
	*x = ClientStreamStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamStringRequest) ProtoMessage() {}

func (x *ClientStreamStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamStringRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamStringRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{8}
}

func (x *ClientStreamStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ClientStreamStringRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *ClientStreamStringRequest) GetRespondWithError() bool {
	if x != nil {
		return x.RespondWithError
	}
	return false
}

type ClientStreamStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClientStreamStringResponse) Reset() {
	*x = ClientStreamStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamStringResponse) ProtoMessage() {}

func (x *ClientStreamStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamStringResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamStringResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ClientStreamStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClientStreamIntRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value            int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Close            bool  `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	RespondWithError bool  `protobuf:"varint,3,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
}

func (x *ClientStreamIntRequest) Reset() {
	*x = ClientStreamIntRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamIntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamIntRequest) ProtoMessage() {}

func (x *ClientStreamIntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamIntRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamIntRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ClientStreamIntRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ClientStreamIntRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *ClientStreamIntRequest) GetRespondWithError() bool {
	if x != nil {
		return x.RespondWithError
	}
	return false
}

type ClientStreamIntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ClientStreamIntResponse) Reset() {
	*x = ClientStreamIntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStreamIntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamIntResponse) ProtoMessage() {}

func (x *ClientStreamIntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamIntResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamIntResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ClientStreamIntResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type BidirectionalStreamStringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value            string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Close            bool   `protobuf:"varint,2,opt,name=close,proto3" json:"close,omitempty"`
	RespondWithError bool   `protobuf:"varint,3,opt,name=respond_with_error,json=respondWithError,proto3" json:"respond_with_error,omitempty"`
}

func (x *BidirectionalStreamStringRequest) Reset() {
	*x = BidirectionalStreamStringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidirectionalStreamStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStreamStringRequest) ProtoMessage() {}

func (x *BidirectionalStreamStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStreamStringRequest.ProtoReflect.Descriptor instead.
func (*BidirectionalStreamStringRequest) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{12}
}

func (x *BidirectionalStreamStringRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BidirectionalStreamStringRequest) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

func (x *BidirectionalStreamStringRequest) GetRespondWithError() bool {
	if x != nil {
		return x.RespondWithError
	}
	return false
}

type BidirectionalStreamStringResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BidirectionalStreamStringResponse) Reset() {
	*x = BidirectionalStreamStringResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TylerSandbox_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BidirectionalStreamStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidirectionalStreamStringResponse) ProtoMessage() {}

func (x *BidirectionalStreamStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_TylerSandbox_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidirectionalStreamStringResponse.ProtoReflect.Descriptor instead.
func (*BidirectionalStreamStringResponse) Descriptor() ([]byte, []int) {
	return file_TylerSandbox_proto_rawDescGZIP(), []int{13}
}

func (x *BidirectionalStreamStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_TylerSandbox_proto protoreflect.FileDescriptor

var file_TylerSandbox_proto_rawDesc = []byte{
	0x0a, 0x12, 0x54, 0x79, 0x6c, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x22, 0x2e, 0x0a, 0x16,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2f, 0x0a, 0x17,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a,
	0x13, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2c, 0x0a, 0x14, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd0, 0x01, 0x0a, 0x19, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2e, 0x0a, 0x13,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x31, 0x0a, 0x15,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x41, 0x74, 0x4e, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3a, 0x0a, 0x1a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x61, 0x74,
	0x5f, 0x6e, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x16, 0x73, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x41, 0x74,
	0x4e, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x1a, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xcd, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x2e, 0x0a, 0x13, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x73,
	0x65, 0x6e, 0x64, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x31, 0x0a, 0x15, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x74, 0x68,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x12, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x74, 0x4e, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x1a, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x16, 0x73, 0x65, 0x6e, 0x64, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x41, 0x74, 0x4e, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2f, 0x0a, 0x17, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x75, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x57, 0x69,
	0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x32, 0x0a, 0x1a, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x72, 0x0a, 0x16, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x77, 0x69, 0x74,
	0x68, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x2f, 0x0a, 0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x7c, 0x0a, 0x20, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x77, 0x69, 0x74, 0x68,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x39,
	0x0a, 0x21, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xa2, 0x05, 0x0a, 0x13, 0x54, 0x79,
	0x6c, 0x65, 0x72, 0x53, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x54, 0x0a, 0x0f, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0c, 0x55, 0x6e, 0x61, 0x72, 0x79,
	0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x12, 0x1b, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62,
	0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x55, 0x6e,
	0x61, 0x72, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x74, 0x67, 0x73,
	0x62, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x56, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70,
	0x62, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5f, 0x0a,
	0x12, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x21, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x56,
	0x0a, 0x0f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x74, 0x12, 0x1e, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x76, 0x0a, 0x19, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e,
	0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e,
	0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x67, 0x73, 0x62, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TylerSandbox_proto_rawDescOnce sync.Once
	file_TylerSandbox_proto_rawDescData = file_TylerSandbox_proto_rawDesc
)

func file_TylerSandbox_proto_rawDescGZIP() []byte {
	file_TylerSandbox_proto_rawDescOnce.Do(func() {
		file_TylerSandbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_TylerSandbox_proto_rawDescData)
	})
	return file_TylerSandbox_proto_rawDescData
}

var file_TylerSandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_TylerSandbox_proto_goTypes = []interface{}{
	(*UnaryCallStringRequest)(nil),            // 0: tgsbpb.UnaryCallStringRequest
	(*UnaryCallStringResponse)(nil),           // 1: tgsbpb.UnaryCallStringResponse
	(*UnaryCallIntRequest)(nil),               // 2: tgsbpb.UnaryCallIntRequest
	(*UnaryCallIntResponse)(nil),              // 3: tgsbpb.UnaryCallIntResponse
	(*ServerStreamStringRequest)(nil),         // 4: tgsbpb.ServerStreamStringRequest
	(*ServerStreamStringResponse)(nil),        // 5: tgsbpb.ServerStreamStringResponse
	(*ServerStreamIntRequest)(nil),            // 6: tgsbpb.ServerStreamIntRequest
	(*ServerStreamIntResponse)(nil),           // 7: tgsbpb.ServerStreamIntResponse
	(*ClientStreamStringRequest)(nil),         // 8: tgsbpb.ClientStreamStringRequest
	(*ClientStreamStringResponse)(nil),        // 9: tgsbpb.ClientStreamStringResponse
	(*ClientStreamIntRequest)(nil),            // 10: tgsbpb.ClientStreamIntRequest
	(*ClientStreamIntResponse)(nil),           // 11: tgsbpb.ClientStreamIntResponse
	(*BidirectionalStreamStringRequest)(nil),  // 12: tgsbpb.BidirectionalStreamStringRequest
	(*BidirectionalStreamStringResponse)(nil), // 13: tgsbpb.BidirectionalStreamStringResponse
}
var file_TylerSandbox_proto_depIdxs = []int32{
	0,  // 0: tgsbpb.TylerSandboxService.UnaryCallString:input_type -> tgsbpb.UnaryCallStringRequest
	2,  // 1: tgsbpb.TylerSandboxService.UnaryCallInt:input_type -> tgsbpb.UnaryCallIntRequest
	4,  // 2: tgsbpb.TylerSandboxService.ServerStreamString:input_type -> tgsbpb.ServerStreamStringRequest
	6,  // 3: tgsbpb.TylerSandboxService.ServerStreamInt:input_type -> tgsbpb.ServerStreamIntRequest
	8,  // 4: tgsbpb.TylerSandboxService.ClientStreamString:input_type -> tgsbpb.ClientStreamStringRequest
	10, // 5: tgsbpb.TylerSandboxService.ClientStreamInt:input_type -> tgsbpb.ClientStreamIntRequest
	12, // 6: tgsbpb.TylerSandboxService.BidirectionalStreamString:input_type -> tgsbpb.BidirectionalStreamStringRequest
	1,  // 7: tgsbpb.TylerSandboxService.UnaryCallString:output_type -> tgsbpb.UnaryCallStringResponse
	3,  // 8: tgsbpb.TylerSandboxService.UnaryCallInt:output_type -> tgsbpb.UnaryCallIntResponse
	5,  // 9: tgsbpb.TylerSandboxService.ServerStreamString:output_type -> tgsbpb.ServerStreamStringResponse
	7,  // 10: tgsbpb.TylerSandboxService.ServerStreamInt:output_type -> tgsbpb.ServerStreamIntResponse
	9,  // 11: tgsbpb.TylerSandboxService.ClientStreamString:output_type -> tgsbpb.ClientStreamStringResponse
	11, // 12: tgsbpb.TylerSandboxService.ClientStreamInt:output_type -> tgsbpb.ClientStreamIntResponse
	13, // 13: tgsbpb.TylerSandboxService.BidirectionalStreamString:output_type -> tgsbpb.BidirectionalStreamStringResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_TylerSandbox_proto_init() }
func file_TylerSandbox_proto_init() {
	if File_TylerSandbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TylerSandbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryCallStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryCallStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryCallIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryCallIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerStreamIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamIntRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStreamIntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidirectionalStreamStringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_TylerSandbox_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BidirectionalStreamStringResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TylerSandbox_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_TylerSandbox_proto_goTypes,
		DependencyIndexes: file_TylerSandbox_proto_depIdxs,
		MessageInfos:      file_TylerSandbox_proto_msgTypes,
	}.Build()
	File_TylerSandbox_proto = out.File
	file_TylerSandbox_proto_rawDesc = nil
	file_TylerSandbox_proto_goTypes = nil
	file_TylerSandbox_proto_depIdxs = nil
}
